Add - added relations between lecturer and quiz, and lecturer and question
AAU-P5-Moodle/moodle-1 pull request #129
Opened 2024-11-12 10:17 UTC by Theis194

# Description
We added methods for appending lecturer id to quiz and questions, and modified existing functions to use these.

## What is added/changed/removed
//Please describe what changes were performed in this pull request

## Issue/fixes reference
//Reference the issue related to this pull request

//Isses: https://github.com/orgs/AAU-P5-Moodle/projects/2/views/1

//If this pull request is not directly related to a github issue, please elaborate on what has been fixed and why

## Testing
//Please explain how to allow PR-reviewers and codeowners on how to test your added functionality

# Checks
- [x] Updated / added tests for these changes
- [x] PHPunit locally passed
- [x] Codesniffer locally passed
- [x] Behat locally passed

2024-11-12 12:14 UTC, od45pv requested changes
Haven't tested it in the IDE. But here's some comments.

2024-11-12 12:21 UTC, ChristofferGamel commented on server/moodle/composer.lock
Necessary for github actions. Tried removing it, everything failed 🙃

2024-11-12 12:23 UTC, mantarias commented on server/moodle/composer.lock
This is removed now

2024-11-12 12:25 UTC, mantarias commented on server/moodle/mod/livequiz/classes/models/livequiz_questions_lecturer_relation.php
> +        return (array) $DB->get_record('livequiz_questions_lecturer', ['lecturer_id' => $lecturerid]);
Because it fails if there is only one question

2024-11-12 12:25 UTC, mantarias commented on server/moodle/mod/livequiz/classes/models/livequiz_questions_lecturer_relation.php
> +        return (array) $DB->get_record('livequiz_questions_lecturer', ['question_id' => $questionid]);
Because it fails if there is only one question

2024-11-12 12:30 UTC, mantarias commented on server/moodle/mod/livequiz/classes/models/livequiz_questions_lecturer_relation.php
> + * Displays the livequiz view page.
Changed this to "Class for relation between question and lecturer"

2024-11-12 13:29 UTC, ChristofferGamel approved these changes

2024-11-12 14:59 UTC, DeeKahy approved these changes

2024-11-13 07:03 UTC, EmilChri commented on server/moodle/mod/livequiz/classes/models/livequiz.php
> +     * Gets the ID for the assimilated course
why assimilated?

2024-11-13 10:33 UTC, EmilChri approved these changes

2024-11-13 10:34 UTC, mantarias commented on server/moodle/mod/livequiz/classes/models/livequiz.php
> +     * Gets the ID for the assimilated course
fixed

2024-11-13 10:35 UTC, mantarias commented on server/moodle/mod/livequiz/classes/models/livequiz.php
> +     * Gets the ID for the assimilated course
fixed

2024-11-13 10:40 UTC, adomasciplys requested changes

2024-11-13 10:40 UTC, adomasciplys commented on server/moodle/composer.lock
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/b794b8a2-b6ea-449e-9681-a326e1ac4282">

composer.lock should be committed to the pull-request. It ensures we all have the same versions of the dependencies we are using

2024-11-13 10:40 UTC, od45pv approved these changes

2024-11-13 10:45 UTC, od45pv commented on server/moodle/composer.lock
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
@DeeKahy

2024-11-13 10:53 UTC, AlliasGhorbani approved these changes

2024-11-13 10:56 UTC, DeeKahy commented on server/moodle/composer.lock
Okay, we are not going to do that because the nix script sets up everything as it should be. If you need to reinstall, you already have a lock file.

We can easily re-add it if it becomes a problem (which I highly doubt).

@adomasciplys please change your review state as soon as possible, unless you completely disagree.

2024-11-13 12:56 UTC, od45pv commented on server/moodle/composer.lock
Does this also apply if you're on windows and not using the Nix script?

2024-11-13 13:24 UTC, adomasciplys approved these changes
Works on our Windows machine 🥇

2024-11-13 13:24 UTC, merged