Db stats retrieval
AAU-P5-Moodle/moodle-1 pull request #136
Opened 2024-11-21 08:52 UTC by ChristofferGamel

# Description
//Describe this PR

## What is added/changed/removed
Implemented a method for retrieving submitted answers from students in the agreed format:

```
questions: [
    question_id1: [student_chooses_answer_id1, student_chooses_answer_id2]
    question_id2: [student_chooses_answer_id3, student_chooses_answer_id4]
]
```
      

## Issue/fixes reference
None, verbal agreement with Team Emil

## Testing
The implemented methods are supposed to be called from the service layer, namely: ```get_student_quiz_results```

# Checks
- [x] Updated / added tests for these changes
- [x] PHPunit locally passed
- [x] Codesniffer locally passed
- [ ] Behat locally passed // No changes relevant for behat

2024-11-21 11:00 UTC, EmilChri approved these changes

2024-11-22 13:33 UTC, Peterrahr commented on server/moodle/mod/livequiz/tests/phpunit/livequiz_service_test.php
>      public function delete_answer(): void {
This is not run, since it is does not contain the prefix test_

In our current branch the test fails, please fix

2024-11-25 07:03 UTC, EmilChri requested changes

2024-11-25 07:03 UTC, EmilChri commented on server/moodle/mod/livequiz/tests/phpunit/livequiz_service_test.php
>      public function delete_answer(): void {
same as Peterrahr but now requesting changes

2024-11-25 12:21 UTC, closed without merging

2024-11-25 12:22 UTC, ChristofferGamel commented
Lukket, da den viser sig ikke længere at være nødvendig