Correct results coloring
AAU-P5-Moodle/moodle-1 pull request #142
Opened 2024-11-26 13:19 UTC by ChristofferGamel

# Description
## What is added/changed/removed
![image](https://github.com/user-attachments/assets/6073527f-0f67-4fba-b6de-ca871c46097a)

## Issue/fixes reference
None, verbal agreement

## Testing
Run a quiz

# Checks
- [x] Updated / added tests for these changes
- [ ] PHPunit locally passed
- [x] Codesniffer locally passed
- [x] Behat locally passed

2024-11-26 14:04 UTC, EmilChri requested changes
There should be made behat tests for this functionality

2024-11-28 09:13 UTC, AndreasBM1 approved these changes
LGTM

2024-11-28 09:13 UTC, vjohns22 approved these changes
MTLG

2024-11-28 10:12 UTC, EmilChri approved these changes

2024-11-28 10:12 UTC, merged