Activity setup
AAU-P5-Moodle/moodle-1 pull request #17
Opened 2024-09-30 10:39 UTC by EmilChri

Activity module setup  has been completed and tested.
It is set up such that that pages for quiz creation can be made.

2024-10-01 19:37 UTC, CarlHejlesen reviewed
Jeg mener det ser meget fornuftigt ud.
Følger moodles snake case.
Går ud fra det er testest på alle i gruppens computere.
Følger deres dokumentation inde for db og hvor plugin skal være.
Fin indsats :D

2024-10-02 06:51 UTC, noobstrikker commented
+points for at update .gitingore efter pratisk brug

2024-10-02 10:00 UTC, DeeKahy commented on .idea/workspace.xml
i skal tilføje den her til git ignore.

2024-10-02 10:02 UTC, DeeKahy requested changes
Is there a good reason to add the workspace.xml? I normally just add the entire .idea folder to the gitignore and untrack it if its tracked.

2024-10-02 10:10 UTC, ChristofferGamel reviewed
Ved ikke, hvad .idea debatten går ud på, men ellers LGTM

2024-10-02 11:02 UTC, adomasciplys commented on .idea/workspace.xml
Has been fixed in 1644dfd53cd2728ab68567e307287322211a823e. Ready for merge after :)

2024-10-02 11:14 UTC, DeeKahy requested changes
This didnt actually delete the file. you have to untrack it.

2024-10-02 11:19 UTC, DeeKahy approved these changes
Very nice <3

2024-10-02 11:20 UTC, merged