Update - fixed upgrade.php
AAU-P5-Moodle/moodle-1 pull request #36
Opened 2024-10-21 11:02 UTC by DaniekFjaes

Now older versions of the database should be upgraded when Moodle is started.

2024-10-21 12:29 UTC, DeeKahy commented
will test it and then approve later today

2024-10-21 13:42 UTC, Laczse reviewed
Looks good generally. My only comment is the naming of the tables. Some of the names such as questions already exists for the normal Moodle quiz. I would therefore suggest that all the tables are named livequiz_tablename instead, such that there are no duplicates and they will be placed together in the table overview. It makes it easier to find the tables, since we have roughly 1500 tables, when having both PHPUnit and Behat installed

2024-10-21 13:45 UTC, Andreas272 requested changes

2024-10-21 13:45 UTC, Andreas272 commented on server/moodle/mod/livequiz/db/upgrade.php
> +        $livequiztable->add_field('course', XMLDB_TYPE_INTEGER, '10', null, XMLDB_NOTNULL, null, '0');
Jeg vil gerne have course_id som navn i stedet for course. (Jomindre jeg har misofrstået noget og det ikke er id'et der er tale om).

2024-10-21 13:45 UTC, Andreas272 commented on server/moodle/mod/livequiz/db/upgrade.php
> +            $dbman->add_field($livequiztable, $courseid);
Når jeg henter branchen ned og opgraderer får jeg en fejl: 'Field "course" already exists' . Jeg ved ikke hvordan jeg er kommet afsted med at få course ind i livequiz-tabellen, men der skal vel tages højde for at den måske eksisterer.

2024-10-21 19:24 UTC, Andreas272 submitted a review, later dismissed

2024-10-22 07:18 UTC, vjohns22 commented
> Looks good generally. My only comment is the naming of the tables. Some of the names such as questions already exists for the normal Moodle quiz. I would therefore suggest that all the tables are named livequiz_tablename instead, such that there are no duplicates and they will be placed together in the table overview. It makes it easier to find the tables, since we have roughly 1500 tables, when having both PHPUnit and Behat installed

Good point. We will look into this. 👍

2024-10-22 11:28 UTC, Laczse approved these changes
Looks great. My only question is why both the answers and the questions have explanation fields?

2024-10-23 06:37 UTC, DeeKahy approved these changes

2024-10-23 08:46 UTC, merged