add - Classes for DB tables
AAU-P5-Moodle/moodle-1 pull request #37
Opened 2024-10-24 12:25 UTC by AndreasBM1

These classes handle interactions with the database. The classes handle insertion of data, some intermediate tables, update, and deletion is still not implemented. 

**The parts of the ER-diagram that this works on**
![image](https://github.com/user-attachments/assets/a4608ce2-d520-424d-98a0-2060c6e827db)

**Below is an example of how to manually insert questions with answers:**
```php

// // These lines are an example of a test quiz:
$test_questions = [new question('Question 1', 'This is question 1.', 256, 'This is the first question.'),
                   new question('Question 2','This is question 2.',64,'There is a question before this one.')];

$test_questions[0]->new_answer_option(0,'Forkert','Den er forkert');
$test_questions[0]->new_answer_option(1,'Rigtig','Den er rigtig');

$test_questions[1]->new_answer_option(0,'Forkert','Den er forkert');
$test_questions[1]->new_answer_option(1,'Rigtig','Den er rigtig');

livequiz::submit_quiz_to_database($instance->id, $test_questions);

$test_quiz = livequiz::get_livequiz_instance($instance->id);

// Check if $test_quiz is an object and then display its properties
echo "<h2>Instance ID: {$instance->id}</h2>";
echo "<h2>Live Quiz Details</h2>";
echo "<p><strong>ID:</strong> $test_quiz->id</p>";
echo "<p><strong>Name:</strong> {$test_quiz->name}</p>";
echo "<p><strong>Course ID:</strong> {$test_quiz->course}</p>";
echo "<p><strong>Introduction:</strong> {$test_quiz->intro}</p>";
echo "<p><strong>Time Created:</strong> " . userdate($test_quiz->timecreated) . "</p>";
echo "<p><strong>Last Modified:</strong> " . userdate($test_quiz->timemodified) . "</p>";
echo "<p><strong>Questions:</strong>" . print_r($test_quiz->questions) . "</p>";

```

2024-10-24 12:49 UTC, Laczse reviewed
I mainly have a few questions. I will approve the pull request, when it passes the codesniffer check

2024-10-24 12:49 UTC, Laczse commented on server/moodle/mod/livequiz/classes/livequiz/livequiz.php
> +{
Does a livequiz not have any attributes?

2024-10-24 12:49 UTC, Laczse commented on server/moodle/mod/livequiz/classes/answers/answers.php
> +    private $explanation;
Why are the answer id not a part of the object? While you should not be able to set or change it, I think it is worth keeping track of

2024-10-24 12:49 UTC, Laczse commented on server/moodle/mod/livequiz/classes/question/question.php
> +    private $title;
The same as with answers.php. Is it not worth tracking the id of the question?

2024-10-24 12:49 UTC, Laczse commented on server/moodle/mod/livequiz/classes/livequiz/livequiz.php
> + * This class is essentially supposed to be static.
Why is this essentially a static class? Will we never work with a livequiz object?

2024-10-28 15:23 UTC, Laczse requested changes
Generally looks good. I have a few naming issues that I think should be solved.
I haven't tested the PR yet. I'll do that tomorrow morning.
Also are there a specific reason for each class having their own folder and namespace?

2024-10-28 15:23 UTC, Laczse commented on server/moodle/mod/livequiz/classes/livequiz/livequiz.php
> +    public function set_question(question $question): void {
Should be named add_question

2024-10-28 15:23 UTC, Laczse commented on server/moodle/mod/livequiz/classes/question/question.php
> +    public function set_answer(answers $answer): void {
Should be named add_answer

2024-10-28 15:23 UTC, Laczse commented on server/moodle/mod/livequiz/classes/answers/answers.php
> +class answers {
Why is the class and file named answers (plural), when both livequiz and question are singular?

2024-10-28 15:23 UTC, Laczse commented on server/moodle/mod/livequiz/classes/livequiz/livequiz.php
> +    public function set_questions(array $questions): void {
Should be named add_questions. Also comment should be changed to appends instead of sets

2024-10-29 07:45 UTC, Laczse approved these changes

2024-10-30 07:54 UTC, DeeKahy submitted a review, later dismissed

2024-10-30 07:55 UTC, DeeKahy commented
> Also are there a specific reason for each class having their own folder and namespace?

Id like to know this as well

2024-10-30 07:56 UTC, ChristofferGamel commented
> > Also are there a specific reason for each class having their own folder and namespace?
> 
> Id like to know this as well

It has been refactored now :) 

![image](https://github.com/user-attachments/assets/4b67a9d9-8eba-4e63-8389-0fd3599bfd3a)

2024-10-31 07:30 UTC, ChristofferGamel approved these changes

2024-10-31 07:34 UTC, Laczse approved these changes

2024-10-31 08:08 UTC, merged